import express from 'express';
import { helloWorld } from './routes';

const app = express();

app.get('/', (request, response) => {
    return response.json({ message: 'Hello World!' });
})

app.listen(3333);

//now it is possible to check on browser: http://localhost:3333/


// Instruction for typescript:
// yarn init -y
// yarn add typescript -D
// yarn add express
// yarn add -D @types/express
// yarn tsc --init
// yarn tsc and then run node./dist/index.js or yarn 
// suggestion: uncomment outDir @ tsconfig.json and modify address to ./dist - all the new js files generated by
// tsc will be available at this folder
// now, just run yarn tsc and all .ts files will be converted to .js files in /dist folder